"""Initial migration

Revision ID: 001_initial
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_variation_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    op.create_index(op.f('ix_wishlist_product_variation_id'), 'wishlist', ['product_variation_id'], unique=False)
    op.create_index(op.f('ix_wishlist_shop_id'), 'wishlist', ['shop_id'], unique=False)
    op.create_index('ix_wishlist_user_id_product_variation_id_shop_id', 'wishlist', ['user_id', 'product_variation_id', 'shop_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wishlist_user_id_product_variation_id_shop_id', table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_shop_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_product_variation_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_table('wishlist')
    # ### end Alembic commands ###
