name: Notify Main Repo

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send update notification to CI/CD repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MAIN_REPO_PAT }}
          repository: developerNihad/ecommerce-wishlist-service
          event-type: update-wishlist-service
          client-payload: '{"service": "wishlist", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
